name: my_tip

on:
    push:
        branches: ['develop']
            
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: My Tip
              uses: ./.github/actions/my_tip
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

